version: '3.7'
x-base:
    &default-base
    image: node:alpine
    volumes:
        - node-modules:/home/node/app/node_modules
        - .:/home/node/app
    working_dir: /home/node/app

services:
    install:
        << : *default-base
        command: npm install

    watch:
        << : *default-base
        command: npm run watch
        ports:
            - 3000:3000
        env_file:
            - .env.development

    serve:
        << : *default-base
        command: npm run serve
        ports:
            - 3000:3000
        env_file:
            - .env

volumes:
    node-modules:
        external: true
